# main.yml
# https://github.com/marketplace/actions/flutter-action
# https://github.com/marketplace/actions/create-release
# 工作流程的名字
name: Build

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - *

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          path: dist/